blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/ThePrismSystem/handbells-used-chart-musicxml/discussions/categories/feature-requests
    about: Suggest a feature in the Feature Requests discussion category.
  - name: Question
    url: https://github.com/ThePrismSystem/handbells-used-chart-musicxml/discussions/categories/q-a
    about: Ask a question in the Q&A discussion category.
